version: '3.9'

services:

  bn.nginx:
    hostname: bn.nginx
    container_name: bn.nginx
    build:
      context: ./docker/development/nginx
    volumes:
      - ./docker/development/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${WEB_SERVER_FORWARD_PORT:-8080}:80"
    networks:
      - breaking-news-network
    depends_on:
      - bn.php-fpm

  bn.php-fpm:
    container_name: bn.php-fpm
    build:
      context: .
      dockerfile: ./docker/development/php/Dockerfile
    volumes:
      - ./:/var/www/app:delegated
      - ./docker/development/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    networks:
      - breaking-news-network

  bn.mysql:
    container_name: bn.mysql
    image: mysql:8.0
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - bn.mysql.data:/var/lib/mysql
    ports:
      - "${MYSQL_SERVER_FORWARD_PORT:-3316}:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-bnews}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-secret}
    networks:
      - breaking-news-network

  bn.rabbitmq:
    container_name: bn.rabbitmq
    image: rabbitmq:management-alpine
    volumes:
      - bn.rabbitmq.data:/var/lib/rabbitmq/mnesia/
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
    ports:
      - "15682:15672"
      - "5682:5672"
    networks:
      - breaking-news-network

  bn.openapi.codegen:
    image: openapitools/openapi-generator-cli:latest
    hostname: bn.openapi.codegen
    volumes:
      - ./spec.yml:/files/spec.yml:delegated
      - ./ts-gen-config.json:/files/ts-gen-config.json:delegated
      - ./../laravel-news-aggregator-openapi:/swagger-ts:delegated
    command: /usr/local/bin/docker-entrypoint.sh generate -g typescript-fetch -i /files/spec.yml -o /swagger-ts -c /files/ts-gen-config.json --global-property skipFormModel=false

volumes:

  bn.rabbitmq.data:
    driver: local
  bn.mysql.data:
    driver: local

networks:

  breaking-news-network:
    name: breaking-news-network
